# Generated by Django 5.1.1 on 2024-10-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('numero_identificacion', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('tipo_identificacion', models.CharField(max_length=2)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(max_length=30)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.SmallIntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('codigo_pertenencia_etnica', models.SmallIntegerField()),
                ('codigo_ocupacion', models.SmallIntegerField()),
                ('codigo_nivel_educativo', models.SmallIntegerField()),
                ('codigo_pais', models.SmallIntegerField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
