# Generated by Django 5.1.1 on 2024-11-17 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_registro',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo_nivel_educativo',
            field=models.SmallIntegerField(choices=[(1, 'Preescolar'), (2, 'Básica Primaria'), (3, 'Básica Secundaria'), (4, 'Media Académica o Clásica'), (5, 'Media Técnica (Bachillerato Técnico)'), (6, 'Normalista'), (7, 'Técnica Profesional'), (8, 'Tecnológica'), (9, 'Profesional'), (10, 'Especialización'), (11, 'Maestría'), (12, 'Doctorado'), (13, 'Ninguno')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo_ocupacion',
            field=models.SmallIntegerField(choices=[(9611, 'Recolectores de basura y material reciclable'), (9612, 'Clasificadores de desechos'), (9613, 'Barrenderos y afines'), (9621, 'Mensajeros, mandaderos, maleteros y repartidores'), (9622, 'Personas que realizan trabajos varios'), (9624, 'Acarreadores de agua y recolectores de leña'), (9625, 'Recolectores de dinero y surtidores de máquinas de venta automática'), (9626, 'Lectores de medidores'), (9629, 'Otras ocupaciones elementales no clasificadas en otros grupos primarios'), (9998, 'Jubilado, desempleado, ama de casa, estudiante, dedicación al hogar, menor de edad'), (9999, 'No informa')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo_pais',
            field=models.SmallIntegerField(choices=[(170, 'COLOMBIA')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo_pertenencia_etnica',
            field=models.SmallIntegerField(choices=[(1, 'Indígena'), (2, 'ROM(gitano)'), (3, 'Raizal(archipiélago de San Andrés y Providencia)'), (4, 'Palanquero de San Basilio'), (5, 'Negro(a) Mulato(a) Afrocolombiano(a) o Afro descendiente'), (6, 'Ninguna de las anteriores'), (7, 'Otro')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_identificacion',
            field=models.CharField(choices=[('AS', 'Adulto Sin identificación'), ('CC', 'Cedula de Ciudadanía'), ('CD', 'Carnet Diplomático'), ('CE', 'Cedula de Extranjería'), ('CN', 'Certificado Nacido vivo'), ('DE', 'Documento Extranjero'), ('MS', 'Menor Sin identificación'), ('PA', 'Pasaporte'), ('PE', 'Permiso Especial de Permanencia'), ('PT', 'Permiso por Protección Temporal'), ('RC', 'Registro Civil'), ('SC', 'Salvoconducto'), ('TI', 'Tarjeta de Identidad')], max_length=2),
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('consecutivo_registro', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_registro', models.SmallIntegerField(default=2)),
                ('codigo_habilitación_ips_primaria', models.BigIntegerField(default=528380048301)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appips.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='recien_nacidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_tamizaje_auditivo_neonatal', models.SmallIntegerField()),
                ('resultado_tamizaje_visual_neonatal', models.SmallIntegerField()),
                ('resultado_oximetria_pre_post_ductal', models.SmallIntegerField()),
                ('fecha_oximetria_pre_post_ductal', models.DateField()),
                ('fecha_tamizaje_auditivo_neonatal', models.DateField()),
                ('fecha_tamizaje_visual_neonatal', models.DateField()),
                ('fecha_tsh_neonatal', models.DateField()),
                ('resultado_tsh_neonatal', models.SmallIntegerField()),
                ('consecutivo_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appips.registro')),
            ],
        ),
        migrations.CreateModel(
            name='primera_infancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Suministro_fortificación_casera', models.SmallIntegerField()),
                ('suministro_de_vitamina_A', models.SmallIntegerField()),
                ('suministro_hierro', models.SmallIntegerField()),
                ('consecutivo_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appips.registro')),
            ],
        ),
        migrations.CreateModel(
            name='no_reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sifilis_gestacional_congenita', models.SmallIntegerField()),
                ('hipotiroidismo_congenito', models.SmallIntegerField()),
                ('lepra', models.SmallIntegerField()),
                ('obesidad_desnutricion', models.SmallIntegerField()),
                ('enfermedad_mental', models.SmallIntegerField()),
                ('cancer_cervix', models.SmallIntegerField()),
                ('dpt_menores', models.SmallIntegerField()),
                ('neumococo', models.SmallIntegerField()),
                ('consulta_psicologia', models.DateField()),
                ('preservativos', models.SmallIntegerField()),
                ('fecha_hemoglobina', models.DateField()),
                ('tratamiento_sifilis_gestacional', models.SmallIntegerField()),
                ('tratamiento_sifilis_congenita', models.SmallIntegerField()),
                ('consecutivo_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appips.registro')),
            ],
        ),
        migrations.CreateModel(
            name='gestacion_menores_hasta_siente_meses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atención_promoción_apoyo_lactancia', models.DateField()),
                ('consecutivo_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appips.registro')),
            ],
        ),
        migrations.CreateModel(
            name='gestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestante', models.SmallIntegerField()),
                ('acido_folico_preconcepcional', models.SmallIntegerField()),
                ('fecha_probable_parto', models.DateField()),
                ('clasificacion_riesgo_gestacional', models.SmallIntegerField()),
                ('fecha_atencion_parto', models.DateField()),
                ('fecha_salida_atencion_parto', models.DateField()),
                ('fecha_primera_consulta_prenatal', models.DateField()),
                ('fecha_ultimo_control_prenatal', models.DateField()),
                ('suministro_acido_folico', models.SmallIntegerField()),
                ('suministro_sulfato_ferroso', models.SmallIntegerField()),
                ('suministro_carbonato_calcio', models.SmallIntegerField()),
                ('consecutivo_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appips.registro')),
            ],
        ),
        migrations.CreateModel(
            name='anticoncepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion_asesoria_anticoncep', models.DateField()),
                ('suministro_metodo_anticoceptivo', models.SmallIntegerField()),
                ('fecha_sumistro_ant', models.DateField()),
                ('consecutivo_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appips.registro')),
            ],
        ),
        migrations.CreateModel(
            name='AgudezaVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agudeza_visual_lejana_ojo_izquierdo', models.SmallIntegerField()),
                ('agudeza_visual_lejana_ojo_derecho', models.SmallIntegerField()),
                ('fecha_valoracion_agudeza_visual', models.DateField()),
                ('consecutivo_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appips.registro')),
            ],
        ),
        migrations.CreateModel(
            name='riesgo_cardiovascular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_tabaco', models.SmallIntegerField()),
                ('resultado_glicemia_basal', models.SmallIntegerField()),
                ('fecha_toma_ldl', models.DateField()),
                ('resultado_ldl', models.BigIntegerField()),
                ('resultado_hdl', models.BigIntegerField()),
                ('resultado_trigliceridos', models.BigIntegerField()),
                ('fecha_toma_hemoglobina', models.DateField()),
                ('resultado_hemoglobina', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fecha_toma_glicemia_basal', models.DateField()),
                ('fecha_toma_creatinina', models.DateField()),
                ('resultado_creatinina', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fecha_toma_hdl', models.DateField()),
                ('clasificacion_riesgo_cardiovascular', models.SmallIntegerField()),
                ('clasificacion_riesgo_metabolico', models.SmallIntegerField()),
                ('fecha_toma_trigliceridos', models.DateField()),
                ('consecutivo_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appips.registro')),
            ],
        ),
        migrations.CreateModel(
            name='salud_bucal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion_salud_bucal', models.DateField()),
                ('cop_por_persona', models.DecimalField(decimal_places=2, max_digits=12)),
                ('consecutivo_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appips.registro')),
            ],
        ),
        migrations.CreateModel(
            name='test_0_12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_tamizaje_vale', models.SmallIntegerField()),
                ('fecha_tamizaje_vale', models.DateField()),
                ('consecutivo_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appips.registro')),
            ],
        ),
        migrations.CreateModel(
            name='test_0_7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_motricidad_gruesa', models.SmallIntegerField()),
                ('resultado_motricidad_finoadaptativa', models.SmallIntegerField()),
                ('resultado_personal_social', models.SmallIntegerField()),
                ('resultado_audicion_lenguaje', models.SmallIntegerField()),
                ('consecutivo_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appips.registro')),
            ],
        ),
        migrations.CreateModel(
            name='test_mayores_60',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_vejez', models.SmallIntegerField()),
                ('consecutivo_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appips.registro')),
            ],
        ),
        migrations.CreateModel(
            name='toda_poblacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_peso', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_talla', models.DateField()),
                ('talla', models.SmallIntegerField()),
                ('resultado_tamizaje_hepatitis_c', models.SmallIntegerField()),
                ('fecha_valoracion_integral', models.DateField()),
                ('fecha_antigeno_hepatitis_b', models.DateField()),
                ('resultado_antigeno_hepatitis_b', models.SmallIntegerField()),
                ('fecha_tamizaje_sifilis', models.DateField()),
                ('resultado_tamizaje_sifilis', models.SmallIntegerField()),
                ('fecha_prueba_vih', models.DateField()),
                ('resultado_prueba_vih', models.SmallIntegerField()),
                ('fecha_tamizaje_hepatitis_c', models.DateField()),
                ('consecutivo_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appips.registro')),
            ],
        ),
    ]
