# Generated by Django 5.1.1 on 2024-11-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appips', '0003_rename_codigo_habilitación_ips_primaria_registro_codigo_habilitacion_ips_primaria_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='registro',
            constraint=models.UniqueConstraint(fields=('id_usuario',), name='unique_registro_por_usuario'),
        ),
    ]
