# Generated by Django 5.1.1 on 2024-11-18 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appips', '0005_remove_registro_unique_registro_por_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appips.usuario'),
        ),
        migrations.AddConstraint(
            model_name='registro',
            constraint=models.UniqueConstraint(fields=('id_usuario',), name='unique_registro_por_usuario'),
        ),
    ]
