# Generated by Django 5.1.1 on 2024-11-18 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appips', '0006_alter_registro_id_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ca_cervix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratamiento_ablativo_escision', models.SmallIntegerField()),
                ('tamizaje_cancer_cuello_uterino', models.SmallIntegerField()),
                ('fecha_tamizaje_cancer_cuello_uterino', models.DateField()),
                ('resultado_tamizaje_cancer_cuello_uterino', models.SmallIntegerField()),
                ('calidad_muestra_citologia', models.SmallIntegerField()),
                ('codigo_habilitacion_ips_cancer_cuello_uterino', models.BigIntegerField()),
                ('fecha_colposcopia', models.DateField()),
                ('fecha_biopsia_cervicouterina', models.DateField()),
                ('resultado_biopsia_cervicouterina', models.SmallIntegerField()),
                ('consecutivo_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appips.registro')),
            ],
        ),
        migrations.CreateModel(
            name='ca_colon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_prueba_sangre_oculta_mf', models.SmallIntegerField()),
                ('resultado_colonoscopia_tamizaje', models.SmallIntegerField()),
                ('fecha_colonoscopia_tamizaje', models.DateField()),
                ('fecha_prueba_sangre_oculta', models.DateField()),
                ('consecutivo_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appips.registro')),
            ],
        ),
        migrations.CreateModel(
            name='ca_mama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_toma_mamografia', models.DateField()),
                ('resultado_mamografia', models.SmallIntegerField()),
                ('fecha_toma_biopsia_mama', models.DateField()),
                ('fecha_resultado_biopsia_mama', models.DateField()),
                ('resultado_biopsia_mama', models.SmallIntegerField()),
                ('consecutivo_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appips.registro')),
            ],
        ),
        migrations.CreateModel(
            name='ca_prostata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_tacto_rectal', models.SmallIntegerField()),
                ('fecha_tacto_rectal', models.DateField()),
                ('fecha_toma_psa', models.DateField()),
                ('resultado_psa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('consecutivo_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appips.registro')),
            ],
        ),
        migrations.CreateModel(
            name='tuberculosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sintomático_respiratorio', models.SmallIntegerField()),
                ('Fecha_baciloscopia', models.DateField()),
                ('Resultado_baciloscopia', models.SmallIntegerField()),
                ('consecutivo_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appips.registro')),
            ],
        ),
    ]
