# Generated by Django 5.1.1 on 2024-12-03 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appips', '0007_ca_cervix_ca_colon_ca_mama_ca_prostata_tuberculosis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gestacion_menores_hasta_siente_meses',
            old_name='fecha_atención_promoción_apoyo_lactancia',
            new_name='fecha_atencion_promocion_apoyo_lactancia',
        ),
    ]
