# Generated by Django 5.1.1 on 2024-12-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appips', '0008_rename_fecha_atención_promoción_apoyo_lactancia_gestacion_menores_hasta_siente_meses_fecha_atencion_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='no_reporte',
            name='cancer_cervix',
            field=models.SmallIntegerField(choices=[(0, 'No aplica'), (21, 'Riesgo no evaluado'), (1845, 'Registrar')], default=0),
        ),
        migrations.AlterField(
            model_name='no_reporte',
            name='consulta_psicologia',
            field=models.DateField(default='1845-01-01'),
        ),
        migrations.AlterField(
            model_name='no_reporte',
            name='dpt_menores',
            field=models.SmallIntegerField(choices=[(0, 'No aplica'), (21, 'Riesgo no evaluado'), (1845, 'Registrar')], default=0),
        ),
        migrations.AlterField(
            model_name='no_reporte',
            name='enfermedad_mental',
            field=models.SmallIntegerField(choices=[(0, 'No aplica'), (21, 'Riesgo no evaluado'), (1845, 'Registrar')], default=21),
        ),
        migrations.AlterField(
            model_name='no_reporte',
            name='fecha_hemoglobina',
            field=models.DateField(default='1845-01-01'),
        ),
        migrations.AlterField(
            model_name='no_reporte',
            name='hipotiroidismo_congenito',
            field=models.SmallIntegerField(choices=[(0, 'No aplica'), (21, 'Riesgo no evaluado'), (1845, 'Registrar')], default=0),
        ),
        migrations.AlterField(
            model_name='no_reporte',
            name='lepra',
            field=models.SmallIntegerField(choices=[(0, 'No aplica'), (21, 'Riesgo no evaluado'), (1845, 'Registrar')], default=21),
        ),
        migrations.AlterField(
            model_name='no_reporte',
            name='neumococo',
            field=models.SmallIntegerField(choices=[(0, 'No aplica'), (21, 'Riesgo no evaluado'), (1845, 'Registrar')], default=0),
        ),
        migrations.AlterField(
            model_name='no_reporte',
            name='obesidad_desnutricion',
            field=models.SmallIntegerField(choices=[(0, 'No aplica'), (21, 'Riesgo no evaluado'), (1845, 'Registrar')], default=21),
        ),
        migrations.AlterField(
            model_name='no_reporte',
            name='preservativos',
            field=models.SmallIntegerField(choices=[(0, 'No aplica'), (21, 'Riesgo no evaluado'), (1845, 'Registrar')], default=0),
        ),
        migrations.AlterField(
            model_name='no_reporte',
            name='sifilis_gestacional_congenita',
            field=models.SmallIntegerField(choices=[(0, 'No aplica'), (21, 'Riesgo no evaluado'), (1845, 'Registrar')], default=0),
        ),
        migrations.AlterField(
            model_name='no_reporte',
            name='tratamiento_sifilis_congenita',
            field=models.SmallIntegerField(choices=[(0, 'No aplica'), (21, 'Riesgo no evaluado'), (1845, 'Registrar')], default=0),
        ),
        migrations.AlterField(
            model_name='no_reporte',
            name='tratamiento_sifilis_gestacional',
            field=models.SmallIntegerField(choices=[(0, 'No aplica'), (21, 'Riesgo no evaluado'), (1845, 'Registrar')], default=0),
        ),
    ]
