# Generated by Django 5.1.1 on 2024-12-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appips', '0009_alter_no_reporte_cancer_cervix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primera_infancia',
            name='Suministro_fortificación_casera',
            field=models.SmallIntegerField(choices=[(0, 'No aplica'), (1, 'Sí se suministra'), (16, 'No se suministra por una tradición'), (17, 'No se suministra por una condición de salud'), (18, 'No se suministra por negación de la usuaria'), (20, 'No se suministra por otras razones'), (21, 'Registro no evaluado')]),
        ),
        migrations.AlterField(
            model_name='primera_infancia',
            name='suministro_de_vitamina_A',
            field=models.SmallIntegerField(choices=[(0, 'No aplica'), (1, 'Sí se suministra'), (16, 'No se suministra por una tradición'), (17, 'No se suministra por una condición de salud'), (18, 'No se suministra por negación de la usuaria'), (20, 'No se suministra por otras razones'), (21, 'Registro no evaluado')]),
        ),
        migrations.AlterField(
            model_name='primera_infancia',
            name='suministro_hierro',
            field=models.SmallIntegerField(choices=[(0, 'No aplica'), (1, 'Sí se suministra'), (16, 'No se suministra por una tradición'), (17, 'No se suministra por una condición de salud'), (18, 'No se suministra por negación de la usuaria'), (20, 'No se suministra por otras razones'), (21, 'Registro no evaluado')]),
        ),
    ]
