# Generated by Django 5.1.1 on 2024-12-04 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appips', '0010_alter_primera_infancia_suministro_fortificación_casera_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primera_infancia',
            old_name='Suministro_fortificación_casera',
            new_name='Suministro_fortificacion_casera',
        ),
    ]
