# Generated by Django 5.1.1 on 2024-12-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appips', '0011_rename_suministro_fortificación_casera_primera_infancia_suministro_fortificacion_casera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recien_nacidos',
            name='resultado_oximetria_pre_post_ductal',
            field=models.SmallIntegerField(choices=[(0, '0-No aplica'), (4, '4-Alterado'), (5, '5-Normal'), (21, '21-Riesgo no evaluado')]),
        ),
        migrations.AlterField(
            model_name='recien_nacidos',
            name='resultado_tamizaje_auditivo_neonatal',
            field=models.SmallIntegerField(choices=[(0, '0-No aplica'), (4, '4-No pasó'), (5, '5-No pasó'), (21, '21-Riesgo no evaluado')]),
        ),
        migrations.AlterField(
            model_name='recien_nacidos',
            name='resultado_tamizaje_visual_neonatal',
            field=models.SmallIntegerField(choices=[(0, '0-No aplica'), (4, '4-Alterado'), (5, '5-Normal'), (21, '21-Riesgo no evaluado')]),
        ),
    ]
