# Generated by Django 5.1.1 on 2024-12-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appips', '0013_alter_recien_nacidos_resultado_tsh_neonatal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_0_12',
            name='resultado_tamizaje_vale',
            field=models.SmallIntegerField(choices=[(0, '0-No aplica'), (4, '4-Falla'), (5, '5-Pasa'), (21, '21-Riesgo no evaluado')]),
        ),
    ]
