# Generated by Django 5.1.1 on 2024-12-06 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appips', '0014_alter_test_0_12_resultado_tamizaje_vale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuberculosis',
            old_name='Sintomático_respiratorio',
            new_name='Sintomatico_respiratorio',
        ),
    ]
