# Generated by Django 5.1.1 on 2024-12-16 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appips', '0015_rename_sintomático_respiratorio_tuberculosis_sintomatico_respiratorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_identificacion',
            field=models.CharField(max_length=18, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El número de identificación debe contener solo dígitos.', regex='^\\d+$')]),
        ),
    ]
