# Generated by Django 5.1.1 on 2024-12-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appips', '0016_alter_usuario_numero_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agudezavisual',
            name='agudeza_visual_lejana_ojo_izquierdo',
            field=models.SmallIntegerField(choices=[(0, '0 -No aplica'), (3, '3 -Menor o igual a 20/20 normal'), (4, '4 -Entre 20/25 y 20/40'), (5, '5 -Mayor o igual de 20/50 hasta 1200 anormal'), (6, '6 -Cuenta dedos'), (7, '7 -Percepción de bultos'), (8, '8 -Proyección y percepción de luz '), (9, '9 -No percibe luz'), (21, '21-Riesgo no evaluado')], default=0),
        ),
    ]
