# Generated by Django 5.1.1 on 2024-12-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appips', '0018_alter_agudezavisual_agudeza_visual_lejana_ojo_derecho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticoncepcion',
            name='suministro_metodo_anticoceptivo',
            field=models.SmallIntegerField(choices=[(0, '0 -No aplica'), (1, '1 -Dispositivo intrauterino'), (2, '2 -Dispositivo intrauterino y preservativo'), (3, '3 -Implante subdérmico'), (4, '4 -Implante subdérmico y preservativo'), (5, '5 -Oral'), (6, '6 -Oral y preservativo'), (7, '7 -Inyectable mensual'), (8, '8 -Inyectable mensual y preservativo '), (9, '9 -Inyectable trimestral'), (10, '10-Inyectable trimestral y preservativo'), (11, '11-Emergencia'), (12, '12-Emergencia y preservativo'), (13, '13-Esterilización'), (14, '14-Esterilización y preservativo'), (15, '15-Preservativo'), (16, '16-No se suministra por una tradición'), (17, '17-No se suministra por una condición de salud'), (18, '18-No se suministra por negación de la usuaria'), (20, '20-No se suministra por otras razones'), (21, '21-Registro no evaluado')]),
        ),
    ]
