# Generated by Django 5.1.1 on 2024-12-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appips', '0019_alter_anticoncepcion_suministro_metodo_anticoceptivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca_cervix',
            name='calidad_muestra_citologia',
            field=models.SmallIntegerField(choices=[(0, '0 -No aplica'), (1, '1 -Satisfactoria Zona de Transformación Presente'), (2, '2 -Satisfactoria Zona de Transformación Ausente'), (3, '3 -Insatisfactoria'), (4, '4 -Rechazada'), (999, '999-No se tiene el dato')]),
        ),
        migrations.AlterField(
            model_name='ca_cervix',
            name='resultado_biopsia_cervicouterina',
            field=models.SmallIntegerField(choices=[(0, '0 -No aplica'), (1, '1 -Negativo para neoplasia '), (3, '3 -NIC de bajo grado (NIC I)'), (4, '4 -NIC de alto grado: (NIC II - NIC III) '), (5, '5 -Neoplasia micro infiltrante: escamocelular o adenocarcinoma'), (6, '6 -Neoplasia Infiltrante: escamocelular o adenocarcinoma'), (21, '21-Riesgo no evaluado')]),
        ),
        migrations.AlterField(
            model_name='ca_cervix',
            name='resultado_tamizaje_cancer_cuello_uterino',
            field=models.SmallIntegerField(choices=[(0, '0  - No aplica'), (1, '1  - ASC-US (células escamosas atípicas de significado indeterminado)'), (2, '2  - ASC-H (células escamosas atípicas, de significado indeterminado sugestivo de LEI de alto grado'), (3, '3  - Lesión intraepitelial escamosa (LEI) de bajo grado- HPV (NIC I) (LEI BG)'), (4, '4  - Lesión intraepitelial escamosa (LEI) de alto grado (NIC II-III CA INSITU) (LEI AG)'), (5, '5  - Lesión intraepitelial escamosa de alto grado sospechosa de infiltración'), (6, '6  - Carcinoma de células escamosas (Escamocelular)'), (7, '7  - Células endocervicales atípicas sin ningún otro significado'), (8, '8  - Células endometriales atípicas sin ningún otro significado'), (9, '9  - Células glandulares atípicas sin ningún otro significado'), (10, '10 - Células endocervicales atípicas sospechosas de neoplasia'), (11, '11 - Células endometriales atípicas sospechosas de neoplasia'), (12, '12 - Células glandulares atípicas sospechosas de neoplasia'), (13, '13 - Adenocarcinoma endocervical in situ'), (14, '14 - Adenocarcinoma endocervical'), (15, '15 - Adenocarcinoma endometrial'), (16, '16 - Otras neoplasias'), (17, '17 - Negativa para lesión intraepitelial o neoplasia'), (18, '18 - Inadecuada para lectura'), (19, '19 - Positivo '), (20, '20 - Negativo'), (21, '21 -Riesgo no evaluado')]),
        ),
        migrations.AlterField(
            model_name='ca_cervix',
            name='tamizaje_cancer_cuello_uterino',
            field=models.SmallIntegerField(choices=[(0, '0 -No aplica'), (1, '1 -Citología cérvico uterina'), (2, '2 -Prueba ADN – VPH'), (3, '3 -Técnica de inspección visual'), (4, '4 -Prueba ADN-VPH y citología cérvico uterina'), (16, '6-No se realiza por una tradición'), (17, '7-No se realiza por una condición de salud '), (18, '8-No se realiza por negación de la usuaria '), (19, '9-No se realiza por tener datos de contacto de la usuaria no actualizados'), (20, '0-No se realiza por otras razones'), (21, '1-Riesgo no evaluado')]),
        ),
        migrations.AlterField(
            model_name='ca_cervix',
            name='tratamiento_ablativo_escision',
            field=models.SmallIntegerField(choices=[(0, '20 -No aplica'), (6, '6 -Sí, se realizó tratamiento ablativo'), (7, '7 -Sí, se realizó tratamiento de escisión'), (8, '8 -Sí, se realizó tratamiento homologable a ablativo o de escisión'), (9, '9 -No se realizó ablación, escisión, ni tratamiento homologable, se requiere de otro procedimiento'), (10, '10-No se realizó ablación ni escisión por otras razones'), (21, '21-Registro no evaluado')]),
        ),
    ]
